export { default as ProjectDetailPage } from './projectPages/ProjectDetailPage';
export { default as ProjectDetailEdit } from './projectPages/ProjectDetailEdit';
export { default as ProjectsOverviewPage } from './projectPages/ProjectsOverviewPage';
export { default as StudentsOverviewPage } from './StudentsOverviewPage';
export { default as RegisterPage } from './RegisterPage';
export { default as AccountPage } from './userPages/AccountPage';
export { default as UserProjectsPage } from './userPages/UserProjectsPage';
export { default as UserNewProjectPage } from './userPages/UserNewProjectPage';
export { default as UserDetailPage } from './userPages/UserDetailPage';